Repository stamdiscord/GamerBot2.0, pull requests merged in 2021-04, with the labels that each got.

#52 Hotfix for issue #49 "Users getting Trusted and other roles one (1) level to early"
  events/guild/message.js
Labels: bug

#45 Devops systems
  CRONSET.sh
  README.md
  STARTME.sh
  package-lock.json
  package.json
Labels: deployment

#54 Fix typo in README.md
  README.md
Labels: enhancement

#57 Fix a bug where memberinfo command would return xpPercentage for the …
  commands/memberinfo.js
Labels: bug

#48 Link fix
  commands/channel_action/linkremove.js
  events/guild/message.js
  functions.js
Labels: enhancement
