Repository stamdiscord/GamerBot2.0, pull requests merged in 2021-03, with the labels that each got.

#5 Create dependabot.yml
  .github/dependabot.yml
Labels: enhancement

#10 Dev 2021-03-11
  GamerBot2.0.js
  commands/channel_action/linkremove.js
  commands/channel_action/moviesuggest.js
  commands/channel_action/videosuggest.js
  commands/confget.js
  commands/confset.js
  commands/emujoin.js
  commands/help.js
  commands/me.js
  commands/memberinfo.js
  commands/on_mention/clockemotion.js
  commands/on_mention/timeget.js
  commands/on_mention/whoareyou.js
  commands/on_question/gaming.js
  commands/on_reaction/moviesuggest_reactionswitcher.js
  commands/on_reaction/videosuggest_reactionswitcher.js
  commands/ping.js
  commands/serverinfo.js
  commands/setxp.js
  commands/suggest.js
  events/client/ready.js
  events/guild/guildMemberAdd.js
  events/guild/message.js
  events/guild/messageReactionAdd.js
  functions.js
  handlers/channel_handler.js
  handlers/command_handler.js
  handlers/event_handler.js
  handlers/mention_handler.js
  handlers/question_handler.js
  handlers/reaction_handler.js
  logos/Blue Wire Logo.png
  logos/Blue Wire Logo.xcf
  logos/Green Wire Logo.png
  logos/Green Wire Logo.xcf
  models/configSchema.js
  models/profileSchema.js
  models/videoSuggestSchema.js
  package-lock.json
  package.json
  workspace.code-workspace
Labels: enhancement

#11 Removal of unnecessary parameters
  GamerBot2.0.js
  commands/channel_action/linkremove.js
  commands/channel_action/moviesuggest.js
  commands/channel_action/videosuggest.js
  commands/confget.js
  commands/confset.js
  commands/emujoin.js
  commands/help.js
  commands/me.js
  commands/memberinfo.js
  commands/on_mention/clockemotion.js
  commands/on_mention/timeget.js
  commands/on_mention/whoareyou.js
  commands/on_question/gaming.js
  commands/on_reaction/moviesuggest_reactionswitcher.js
  commands/on_reaction/videosuggest_reactionswitcher.js
  commands/ping.js
  commands/serverinfo.js
  commands/setxp.js
  commands/suggest.js
  events/client/ready.js
  events/guild/guildMemberAdd.js
  events/guild/message.js
  events/guild/messageReactionAdd.js
  handlers/channel_handler.js
  handlers/command_handler.js
  handlers/event_handler.js
  handlers/mention_handler.js
  handlers/question_handler.js
  handlers/reaction_handler.js
Labels: enhancement

#7 Add a README
  README.md
Labels: documentation

#18 Dev 2021-03-19
  .replit
  GamerBot2.0.js
  commands/channel_action/linkremove.js
  commands/channel_action/moviesuggest.js
  commands/channel_action/videosuggest.js
  commands/confget.js
  commands/confset.js
  commands/emujoin.js
  commands/help.js
  commands/me.js
  commands/memberinfo.js
  commands/on_mention/clockemotion.js
  commands/on_mention/dateget.js
  commands/on_mention/timeget.js
  commands/on_mention/whoareyou.js
  commands/on_question/gaming.js
  commands/on_reaction/moviesuggest_reactionswitcher.js
  commands/on_reaction/videosuggest_reactionswitcher.js
  commands/ping.js
  commands/serverinfo.js
  commands/setxp.js
  commands/suggest.js
  commands/ticket.js
  commands/uptime.js
  events/client/ready.js
  events/guild/guildMemberAdd.js
  events/guild/message.js
  events/guild/messageReactionAdd.js
  functions.js
  handlers/channel_handler.js
  handlers/command_handler.js
  handlers/event_handler.js
  handlers/mention_handler.js
  handlers/question_handler.js
  handlers/reaction_handler.js
  models/configSchema.js
  models/profileSchema.js
  package-lock.json
  package.json
Labels: bug, enhancement

#33 Dev 2021-03-25
  commands/confset.js
  commands/memberinfo.js
  commands/on_mention/dateget.js
  commands/setxp.js
  commands/suggest.js
  commands/ticket.js
  commands/uptime.js
  commands/xptoplist.js
  events/guild/message.js
  functions.js
  models/configSchema.js
  models/profileSchema.js
  models/videoSuggestSchema.js
Labels: bug, enhancement

#34 Make leaderboard better
  commands/me.js
  commands/memberinfo.js
  commands/xptoplist.js
Labels: bug, enhancement, feature request

#38 Fix leaderboard bugs
  commands/memberinfo.js
  commands/xptoplist.js
Labels: bug
